/* eslint-disable */
export default {
  "key": "preorder-form",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "checkoutDetails": "Checkout Details",
        "fullNameLabel": "Full Name",
        "fullNamePlaceholder": "Somchai Jaidee",
        "socialLabel": "Social (LINE/FB)",
        "socialPlaceholder": "LINE ID / FB Name",
        "phoneLabel": "Phone Number",
        "phonePlaceholder": "081-234-5678",
        "shippingMethodLabel": "Shipping Method",
        "pickupLabel": "Pick up at School (Free)",
        "postalLabel": "Postal (+฿50)",
        "addressLabel": "Delivery Address",
        "addressPlaceholder": "Street, District, Province, Postal Code",
        "totalAmount": "Total Amount",
        "goToPayment": "Go to Payment",
        "cartEmpty": "Your cart is empty",
        "scanToPay": "Scan to Pay",
        "totalToPay": "Total to pay",
        "recipientName": "MWIT Student Committee",
        "transferInstruction": "Please transfer exactly",
        "uploadSlip": "Upload Payment Slip",
        "fileType": "JPG, PNG (Max 5MB)",
        "backToDetails": "Back to details",
        "orderSuccessful": "Order Successful!",
        "orderPlacedMessage": "Order has been placed. We'll verify your payment shortly.",
        "linkedAccount": "This order is linked to your account.",
        "trackOrder": "Track Order",
        "signInPrompt": "Sign in with Google to track this order and see all your order history.",
        "signInButton": "Sign in to Track",
        "continueShopping": "Continue Shopping",
        "nameRequired": "Name is required",
        "socialRequired": "Social contact is required",
        "phoneRequired": "Phone number is required",
        "addressRequired": "Address is required for postal shipping"
      },
      "th": {
        "checkoutDetails": "ข้อมูลการจัดส่ง",
        "fullNameLabel": "ชื่อ-นามสกุล",
        "fullNamePlaceholder": "สมชาย ใจดี",
        "socialLabel": "ช่องทางติดต่อ (LINE/FB)",
        "socialPlaceholder": "ไอดีไลน์ / ชื่อเฟสบุ๊ค",
        "phoneLabel": "เบอร์โทรศัพท์",
        "phonePlaceholder": "081-234-5678",
        "shippingMethodLabel": "วิธีการจัดส่ง",
        "pickupLabel": "รับที่โรงเรียน (ฟรี)",
        "postalLabel": "จัดส่งพัสดุ (+฿50)",
        "addressLabel": "ที่อยู่จัดส่ง",
        "addressPlaceholder": "บ้านเลขที่, ตำบล, อำเภอ, จังหวัด, รหัสไปรษณีย์",
        "totalAmount": "ยอดรวมทั้งหมด",
        "goToPayment": "ดำเนินการชำระเงิน",
        "cartEmpty": "ตะกร้าสินค้าว่างเปล่า",
        "scanToPay": "สแกนเพื่อชำระเงิน",
        "totalToPay": "ยอดที่ต้องชำระ",
        "recipientName": "คณะกรรมการนักเรียน MWIT",
        "transferInstruction": "กรุณาโอนเงินจำนวน",
        "uploadSlip": "อัปโหลดสลิปโอนเงิน",
        "fileType": "JPG, PNG (ขนาดไม่เกิน 5MB)",
        "backToDetails": "ย้อนกลับ",
        "orderSuccessful": "สั่งซื้อสำเร็จ!",
        "orderPlacedMessage": "ได้รับคำสั่งซื้อแล้ว เราจะตรวจสอบการชำระเงินของท่านโดยเร็วที่สุด",
        "linkedAccount": "คำสั่งซื้อนี้ถูกผูกกับบัญชีของคุณแล้ว",
        "trackOrder": "ติดตามสถานะ",
        "signInPrompt": "เข้าสู่ระบบด้วย Google เพื่อติดตามสถานะและดูประวัติการสั่งซื้อ",
        "signInButton": "เข้าสู่ระบบเพื่อติดตาม",
        "continueShopping": "ซื้อสินค้าต่อ",
        "nameRequired": "กรุณากรอกชื่อ",
        "socialRequired": "กรุณากรอกช่องทางติดต่อ",
        "phoneRequired": "กรุณากรอกเบอร์โทรศัพท์",
        "addressRequired": "กรุณากรอกที่อยู่สำหรับการจัดส่ง"
      }
    }
  },
  "localIds": [
    "preorder-form::local::components/preorder/PreorderForm.content.ts"
  ]
} as const;
